# Generated by Django 6.0.3 on 2026-03-05 17:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('boolean', 'Да/Нет')], max_length=20, verbose_name='Тип')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'indexes': [models.Index(fields=['name'], name='cart_attrib_name_2a7809_idx'), models.Index(fields=['type'], name='cart_attrib_type_5c6523_idx')],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='cart_brand_name_07dfa9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cart.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='cart.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cart.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текстовое значение')),
                ('number_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Числовое значение')),
                ('boolean_value', models.BooleanField(blank=True, null=True, verbose_name='Логическое значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='cart.attribute', verbose_name='Характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='cart.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристик',
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Артикул может содержать только заглавные буквы,цифры и дефис', regex='^[A-Z0-9-]+$')], verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='cart.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Вариация',
                'verbose_name_plural': 'Вариации',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ID склада')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('reserved', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарезервировано')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='cart.variation', verbose_name='Вариация')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='cart_catego_name_6d42a6_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='cart_catego_parent__a19e68_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='cart_produc_brand_i_784645_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='cart_produc_categor_aa68a5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='cart_produc_created_379fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['attribute'], name='cart_attrib_attribu_666496_idx'),
        ),
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['product'], name='cart_attrib_product_2f1142_idx'),
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('text_value__isnull', False), ('number_value__isnull', True), ('boolean_value__isnull', True)), models.Q(('text_value__isnull', True), ('number_value__isnull', False), ('boolean_value__isnull', True)), models.Q(('text_value__isnull', True), ('number_value__isnull', True), ('boolean_value__isnull', False)), _connector='OR'), name='only_one_value_field_filled'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'product')},
        ),
        migrations.AddIndex(
            model_name='variation',
            index=models.Index(fields=['product'], name='cart_variat_product_0844fa_idx'),
        ),
        migrations.AddIndex(
            model_name='variation',
            index=models.Index(fields=['sku'], name='cart_variat_sku_ac32f2_idx'),
        ),
        migrations.AddIndex(
            model_name='variation',
            index=models.Index(fields=['is_active'], name='cart_variat_is_acti_a33d77_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['variation'], name='cart_stock_variati_82e609_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['warehouse_id'], name='cart_stock_warehou_071622_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('quantity'))), name='reserved_lte_quantity'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('variation', 'warehouse_id')},
        ),
    ]
