# Generated by Django 6.0.3 on 2026-03-05 17:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?[0-9\\-\\s()]+$')], verbose_name='Телефон')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=5, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=10, verbose_name='Квартира')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Индекс')),
                ('is_default', models.BooleanField(default=True, verbose_name='Основной адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'indexes': [models.Index(fields=['user'], name='users_addre_user_id_826d51_idx')],
            },
        ),
    ]
